# --- Diagnostic mode ---

# Prevent sleep/deep-sleep variables from confusing the test
CONFIG_ZMK_SLEEP=n

# BLE stability tests
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Clone-board oscillator workaround
# Helps if the external low-frequency crystal/clock circuit is bad or unstable.
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Logging
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_DEFAULT_LEVEL=3
